### ISSUE TITLE
Should as.ctd(argo) allow for profile number specification?

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1171]
From #1170. One thing I was thinking would be nice would be to have an argument in `as.ctd()` that allows you to specify *which* profile you'd like to pull out of the `argo` object (instead of just taking the first one, though I think that should be the default behaviour).

Something like:
```r
data(argo)
plot(as.ctd(argo, profile=10))
```
The `profile` argument is ignored unless it is of `argo`-class.

**Comment by richardsc** [comment]
Currently, this would be accomplished by first converting the `argo` object to a `section` (which is sensible if one is working with all the profiles), but is a little cumbersome, e.g.
```r
data(argo)
plot(as.section(argo)[['station']][[10]])
```

**Comment by dankelley** [comment]
Yes, I like the idea of `profile` argument. I see you've assigned yourself -- sweet. But note that I did stuff in `dk` that gets partway there (including documentation).  To avoid merge confusion, perhaps  this issue can be put on hold until `dk` gets merged into `develop` (likely tomorrow morning).

**Comment by richardsc** [comment]
See PR #1172

**Comment by dankelley** [comment]
I merged and did a slight enhancement (checking `profile` value against matrix `ncol`, etc) in `develop` commit 7c383e4c63438ae7b745383aa81706845caae430.

It's up to Clark to close this but can I add a tangent?

As shown below, the flags are coming out `NA` in this case. I didn't think that was a valid argo flag. DO you think this is something that `read.argo` should check for, Clark?  I'm giving the filename. It came from the url named in the first paragraph.

```R
> d
argo object, from file '/Users/kelley/Dropbox/argo-test/nodc_R6902653_027.nc', has data as follows.
   time: 2016-12-05 19:38:00, 2016-12-05 19:38:00 (length 2)
   latitude: -10.31, -10.31 (length 2)
   longitude: -14.948, -14.948 (length 2)
   pressure, a 145x2 array with value 6 at [1,1] position
   temperature, a 145x2 array with value 24.729 at [1,1] position
   salinity, a 145x2 array with value 36.516 at [1,1] position
> head(d[["flags"]]$temperature, 22)
      [,1] [,2]
 [1,]    1    3
 [2,]    1    1
 [3,]    1    1
 [4,]    1    1
 [5,]    1    1
 [6,]    1   NA
 [7,]    1   NA
 [8,]    1   NA
 [9,]    1   NA
[10,]    1   NA
[11,]    1   NA
[12,]    1   NA
[13,]    1   NA
[14,]    1   NA
[15,]    1   NA
[16,]    1   NA
[17,]    1   NA
[18,]    1   NA
[19,]    1   NA
[20,]    1   NA
[21,]    1   NA
[22,]    1   NA
```

**Comment by richardsc** [comment]
I still don't really know where those files come from, or how they are generated. The aren't consistent with the "true" Argo data files (either the multi-profile ones or the single profile ones) that can be found on the Argo GDACs, so I don't think it's worth spending time trying to support them.

You should also note that the NA flags are for the second profile in that file, which isn't a real profile as it only has 5 points near the surface and all the rest of the rows are also NAs.

I'll close now, since this seems to work as stated in the title.

**Comment by dankelley** [comment]
Good, thanks. As a comment, it really is hard knowing how to get argo data. One of the reasons I like the site from which I got these data (https://data.nodc.noaa.gov/argo/data/atlantic/2016/12/) is that at another spot on the site, there are inventories. Thus, the following works to make a world map (used in OAR ... shows how to project, how to paste, how to loop, etc, so a good example). I have had a hard time finding inventory data on other servers ... but I'm likely just not seeing where they are, somehow.
```R
library(oce)
data(coastlineWorld)
if (!interactive()) pdf("argo1.pdf", height=4, pointsize=10)
mapPlot(coastlineWorld,projection="+proj=wintri",col='gray')
for (basin in c("atlantic", "pacific", "indian")) {
    url <- paste("https://data.nodc.noaa.gov/argo/inv/basins/",
                 basin, "/2016/", substr(basin, 1, 2),
                 "201612_argoinv.txt", sep="")
    message(url)
    d <- read.csv(url)
    mapPoints(d$longitude_min, d$latitude_min, pch=20, cex=0.4)
}

if (!interactive()) dev.off()
```

**Comment by richardsc** [comment]
That's a good point about the inventories ... They must exist somewhere. I recall Howard talking about doing searches through the lists of floats (active, inactive, etc) at that BGC Argo meeting, so there must be other places to search metadata. They might not be public facing, but maybe we should just ask?

**Comment by richardsc** [comment]
This link has some information about more general looking index files:

http://www.argo.ucsd.edu/Data_FAQ.html#browse

Which leads to this site:

ftp://usgodae.org/pub/outgoing/argo

I'm guessing [this file](ftp://usgodae.org/pub/outgoing/argo/ar_index_global_prof.txt.gz) would be useful for searching for specific float files, but beware that it's a 29MB zipped txt file.

**Comment by richardsc** [comment]
This should be in a new issue ... going to move.
