### ISSUE TITLE
problem reading met file inst/extdata/test_met_vsn1.csv

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1643]
I decided to try out appveyor for continuous checking (since sf uses it, as well as travisCI), and it found an error (https://ci.appveyor.com/project/dankelley/oce-5h53v#L919) that I cannot reproduce locally or in travisCI.

Maybe this is because the file has an accented character?

This error may indicate that appveyor will be handy in finding problems ... or it may suggest that it will *cause* problems with false positives. In any case, I intend to keep it for a few weeks at least, in the hopes that it will have intermittent failures less often (or at least at different times than) travisCI.

**Comment by dankelley** [comment]
Hm. I made the error message display the line that it was failing to recognize, and the result is
```R
Error in read.met(system.file("extdata", "test_met_vsn2.csv", package = "oce")) :  cannot determine file type from file contents; first line is '<U+FEFF>"Longitude (x)","Latitude (y)","Station Name","Climate ID","Date/Time","Year","Month","Day","Time","Temp (�C)","Temp Flag","Dew Point Temp (�C)","Dew Point Temp Flag","Rel Hum (%)","Rel Hum Flag","Wind Dir (10s deg)","Wind Dir Flag","Wind Spd (km/h)","Wind Spd Flag","Visibility (km)","Visibility Flag","Stn Press (kPa)","Stn Press Flag","Hmdx","Hmdx Flag","Wind Chill","Wind Chill Flag","Weather"'
```
Notice that `<U+FEFF>` at the start.  I googled for that and found that this is a "zero width invisible" character, that excel inserts.  That was breaking my `grepl()` call.

For more on this weird character, see this interesting essay: https://www.freecodecamp.org/news/a-quick-tale-about-feff-the-invisible-character-cd25cd4630e7/

**Comment by dankelley** [comment]
Fixed, by altering `grep` commands, on both the pattern and the `usebytes` argument. (I don't know which fixed the problem, to be honest.)

**Comment by richardsc** [comment]
Wait. Are you saying somewhere in the Government of Canada data export pipeline the CSV files are being manipulated by Excel??? While it wouldn’t surprise me that much, I still can’t really believe that their IT department would do something that ridiculous. 

I wonder if those characters have always been there or if it’s a recent thing?

**Comment by dankelley** [comment]
I've no idea on whether the file went through excel on my machine, although I doubt it a bit. The problem has never cropped up until this appveyor test.  Maybe they set up something stringent, and macos (and linux etc) are clever enough to check for that first character and remove it before R/readline tried to read the data.

This is something to be on the lookout for, if a `grep` fails in a file. This grep call was insisting that the pattern attached to the start of the line, because I did not want any false positives.  I fixed it by allowing zero or 1 character between start-of-line and the `"` mark.  (Also I dropped the `useBytes` arg, but I don't know if that is what solved it ... I just figured I'd do a test without an arg that I do not really understand and the test worked so I left out the arg I didn't understand.)

I think I've read about this zero-width non-printing character before, but cannot recall ever having to handle it.

Notice that a hex dump does not say `<U+FEFF>` (which is what R is getting), but rather `bbef`.  See https://en.wikipedia.org/wiki/Byte_order_mark for more context ... but this is a pit that I'd prefer to glance at from above, rather than jump into.  But this issue is a good one to have in our memory, in case a weird problem comes up at some time. I think it will only be an issue if we are using `grep` with pattern `^SOMETHING`.
```
$ od -x inst/extdata/test_met_vsn2.csv | head -1
0000000      bbef    22bf    6f4c    676e    7469    6475    2065    7828
```
